name: GameModes
version: 0.1
author: VargaSzabolcs
main: me.vargaszabolcs.gamemodes.GameModes
api-version: 1.15
commands:
  fort:
    description: Sets up the basics for playing fort game! Try /fort start and /fort stop.
    usage: